apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb0
  template:
    metadata:
      labels:
        app: couchdb0
        tier: database
        track: stable
    spec:
      nodeSelector:
        kubernetes.io/hostname: poc3
      containers:
        - name: couchdb0
          image: "hyperledger/fabric-couchdb:latest"
          env:
            - name: COUCHDB_USER
              value: ""
            - name: COUCHDB_PASSWORD
              value: ""
          ports:
            - name: couchdb0-port
              containerPort: 5984
